### ISSUE TITLE
After click on select the input box is empty

### ISSUE THREAD

**Issue by kapilpaul** [moreta/vue-search-select#89]
Hi,

This package is giving me what I want. I am using model-list-select. Here is my code,
`<model-list-select :list="productItems"
                                                       option-value="id"
                                                       :custom-text="optionDisplayText"
                                                       v-model="purchase['products'].product_id"
                                                       placeholder="select item"
                                                       @searchchange="searchProduct"></model-list-select>` 

when I search I am getting the result on the drop-down. but when click on an item then the input box is empty and there is no data is set on v-model property.

This is my methods,

<pre>
searchProduct (searchText) {
                this.searchText = searchText;
                if(this.searchText != '') {
                    this.$axios.get('products/search/' + this.searchText, this.$auth.getHeader()).then(response => {
                        this.productItems = response.data.products.data;
                    }).catch(error => {
                        console.log(error.response);
                    });
                }
            },
            optionDisplayText (product) {
                return `${product.name} - ${product.model}`
            }
</pre>

Can you please help?

**Comment by moreta** [comment]
Maybe your product.id type is integer right?
I found bug,  when optionValue's type is integer value is don't properly set.

I'll fix it in a hurry.

**Comment by moreta** [comment]
fixed at v.2.6.2

On Before version. 
When init value undefined or null, number value do not recognized.
And ''(empty string)
I add defence for "falsy" initial value.

<https://github.com/moreta/vue-search-select/commit/7f59d5b47f86b660d63fe8a516a393ba429e57f6>

To better support, may be we need prop for value type.

**Comment by juljupy** [comment]
Hi thanks for this great component.

I'm testing last release 2.8.2 and this issue is still present.

When option-value is a number, the input value is set to empty string.

Have a nice day!.

**Comment by moreta** [comment]
hmm..
@juljupy 
I think this issue fixed. You can check. Number type Option Value ModelList sample code
https://moreta.github.io/vue-search-select/#/ModelList

Can i see the code?

**Comment by juljupy** [comment]
Hi,

In this link you can see the issue:
https://codesandbox.io/s/mz60njjw09

**Comment by juljupy** [comment]
Hello.

Hope @moreta have been fine, I just want to ask if you already check this issue out?

Thanks.

**Comment by moreta** [comment]
@juljupy I check your code.
This is not a number value problem.
This is name value problem.

Currently there are limitation reference input value by name.
To reference input value by name, option-value and option-text should be same.
https://codesandbox.io/s/4zo1or59m7

I also hope to fix this, but this tricky. Because input value used by display text.

I recommend, form value reference through data's object.
And submit also do with component's method and submit(or send by ajax) by js code.

**Comment by juljupy** [comment]
Hi,

Ok, thank you for your response.
